allow-branch = ["main"]
push = true
tag = true
publish = true
verify = true
pre-release-commit-message = "Bump version to {{version}}"
tag-message = "{{version}}"
tag-name = "{{version}}"
dev-version = false
enable-features = ["k8s-openapi/v1_24"]
