allow-branch = ["main", "HEAD"]
push = true
tag = true
publish = true
verify = true
pre-release-commit-message = "Bump version to {{version}}"
tag-message = "{{version}}"
tag-name = "{{version}}"
enable-features = ["k8s-openapi/latest"]
